id: P003199
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1PD159435
  title: 'སྲིན་པོ་གཡུ་རྔོག་དང་ཉི་མ་ལྷ་ས། '
  author: ''
  volumes:
    86e99727081b437ea6cbcd4caa39032a:
      image_group_id: I2PD18277
      title: ''
      volume_number: 1
      total_pages: 288
      base_file: v001.txt
